### ISSUE TITLE
[bug] .stream must return stream instance

### ISSUE THREAD

**Issue by ghost** [ahlwong/dakota-cassandra#1]
In my code i heavily rely on streaming API. Even if you didn't implement query buffering yet, please return Stream instance.
1. https://github.com/ahlwong/dakota-cassandra/blob/c94c8b5971ce7f5be75edd3abcab3165ac62cd38/lib/index.js#L417
2. https://github.com/ahlwong/dakota-cassandra/blob/71954bc72bf771106a6b081880c8e4492b6956f9/lib/model.js#L1453

P. S. Awesome ODM! Best of all that i've been seen in NPM! Keep up the good work!

**Comment by ahlwong** [comment]
#### Here's what changed:
- All streams returned by DakotaCassandra are now `WrappedStreams`.
- You set event handlers via `on(event, callback)` where `event` is `'readable'`, `'end'`, `'error'` just like on Cassandra's native stream object
- `WrappedStream`'s instance method `.read` now returns `Model` instances instead of `Rows`

#### Here's an example on how to use streams:

``` javascript
  var stream = User.stream()
  .on('readable', function () {
    //readable is emitted as soon a row is received and parsed
    var user;
    while (user = this.read()) {
      console.log(user instanceof User);
    }
  })
  .on('end', function () {
    //stream ended, there aren't any more rows
    console.log('stream ended');
  })
  .on('error', function (err) {
    //Something went wrong: err is a response error from Cassandra
    console.log('stream error');
    console.log(err);
  });
```
