### ISSUE TITLE
[bug] Model.upsert isn't working when you pass Row as first parameter.

### ISSUE THREAD

**Issue by ghost** [ahlwong/dakota-cassandra#2]
http://pastebin.com/i936Hg7z

At line 28 we have valid `project` but
- all columns with type `uuid` are instances of Uuid
- project is instance of Row

Because `upsert` expects assignments to be plain object, `Model.upsert(project, cb)` fails.

**Comment by ahlwong** [comment]
I just committed a fix to your previous bug that addresses this.

#### Here's what changed:
- All streams returned by DakotaCassandra are now `WrappedStreams`.
- You set event handlers via `on(event, callback)` where `event` is `'readable'`, `'end'`, `'error'` just like on Cassandra's native stream object
- `WrappedStream`'s instance method `.read` now returns `Model` instances instead of `Rows`

#### Here's how to fix your current bug with the previous fix:
1. Now that you have `model` instances instead of `rows`...
   - the `uuid` field will be a `String` like you expect
2. You can get a `plain object` by calling the mass-get method `.get([col1{String}, col2{String}, ...])` on the `model` instances
3. You can then pass the `plain object` result of the mass-get to `.upsert`

#### Here's an example on how to use streams:

``` javascript
  var stream = User.stream()
  .on('readable', function () {
    //readable is emitted as soon a row is received and parsed
    var user;
    while (user = this.read()) {
      console.log(user instanceof User);
    }
  })
  .on('end', function () {
    //stream ended, there aren't any more rows
    console.log('stream ended');
  })
  .on('error', function (err) {
    //Something went wrong: err is a response error from Cassandra
    console.log('stream error');
    console.log(err);
  });
```
